# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ourteam_employee', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=48, verbose_name='name')),
                ('title', models.CharField(max_length=48, verbose_name='title')),
                ('image', smartfields.fields.ImageField(blank=True, default='ourteam/default.jpg', upload_to='ourteam/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('twitter', models.CharField(max_length=24, verbose_name='twitter')),
                ('linkedin', models.CharField(max_length=24, verbose_name='linkedin')),
            ],
            options={
                'db_table': 'employee',
                'verbose_name_plural': 'employee',
                'verbose_name': 'employee',
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, 'cms.cmsplugin'),
        ),
    ]
