# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('services', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='services',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='services',
        #     name='cmsplugin_ptr',
        #     field=models.OneToOneField(default=models.CharField(max_length=24, verbose_name='title'), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        # ),
    ]
