# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170119_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/%Y/%m/%d'),
        ),
    ]
