# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170119_1419'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='services',
        #     name='cmsplugin_ptr',
        #     field=models.OneToOneField(default=models.CharField(max_length=24, verbose_name='title'), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        # ),
    ]
