# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170119_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='services_services', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
    ]
