# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-22 18:55
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170120_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=smartfields.fields.ImageField(upload_to='services/%Y/%m/%d'),
        ),
    ]
