# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20170123_1358'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='services',
        #     name='id',
        # ),
    ]
