# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_services_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
    ]
