# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aboutus_aboutus', serialize=False, to='cms.CMSPlugin')),
                ('synopsis', tinymce.models.HTMLField(verbose_name='textfield')),
            ],
            options={
                'db_table': 'aboutus',
                'verbose_name_plural': 'aboutus',
                'verbose_name': 'aboutus',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
