# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contactus_contactus', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=48, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'get_latest_by': 'created',
                'verbose_name': 'contactus',
                'db_table': 'contactus',
                'ordering': ('-created',),
                'verbose_name_plural': 'contactus',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
