# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_portfolio', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=24, verbose_name='title')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/%d')),
                ('manufacturer1', models.CharField(max_length=15, verbose_name='manufacturer1')),
                ('manufacturer2', models.CharField(max_length=15, verbose_name='manufacturer2')),
                ('manufacturer3', models.CharField(max_length=15, verbose_name='manufacturer3')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name_plural': 'portfolios',
                'verbose_name': 'portfolio',
                'db_table': 'portfolio',
                'get_latest_by': 'created',
                'ordering': ('-created',),
            },
            bases=('cms.cmsplugin',),
        ),
    ]
