# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='manufacturer1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='manufacturer2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='manufacturer3',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='place holder', max_length=15, verbose_name='description'),
            preserve_default=False,
        ),
    ]
