# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170120_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=48, verbose_name='description'),
        ),
    ]
