# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='synopsis',
            field=models.TextField(default='place jolding', verbose_name='textfield'),
            preserve_default=False,
        ),
    ]
