# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-22 18:55
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=smartfields.fields.ImageField(upload_to='portfolio/%Y/%m/%d'),
        ),
    ]
