# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170122_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/%Y/%m/%d'),
        ),
    ]
