# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('name', models.CharField(max_length=48, unique=True, verbose_name='name')),
                ('location', models.CharField(max_length=48, unique=True, verbose_name='location')),
                ('created', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='created')),
            ],
            options={
                'db_table': 'NewEmployee',
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'verbose_name': 'NewEmployee',
            },
        ),
    ]
