# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedForms',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customerportal_generatedforms', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=48, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'db_table': 'customerformodel',
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'verbose_name': 'customerformmodel',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
