# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='location',
            field=models.CharField(max_length=48, verbose_name='location'),
        ),
    ]
