# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customerportal_newemployee', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='name')),
                ('location', models.CharField(max_length=48, unique=True, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'NewEmployee',
                'get_latest_by': 'created',
                'ordering': ('-created',),
                'db_table': 'NewEmployee',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='generatedforms',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='GeneratedForms',
        ),
    ]
