# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('customerportal', '0002_auto_20170914_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployeePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customerportal_newemployeepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Optional. Title of the widget.', max_length=64, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='newemployee',
            name='cmsplugin_ptr',
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='created'),
        ),
    ]
